### ISSUE TITLE
Support for functional components

### ISSUE THREAD

**Issue by raunofreiberg** [atlassian/extract-react-types#110]
Currently it seems like only classes will be parsed. Is it possible to add support for parsing functional components?

**Comment by Noviny** [comment]
Functional components should work if they are the default export of the passed in file, or using the [babel plugin](https://github.com/atlassian/extract-react-types/tree/master/packages/babel-plugin-extract-react-types) instead of the webpack loader (Note: the babel plugin has some performance concerns if you included it in anything particularly large)

I'm going to close this, but feel free to reopen/comment further if you need a further solution.

(the reasons it only supports default exports is a design constraint at the moment that we won't have time to solve for and gets gnarly quickly)

**Comment by raunofreiberg** [comment]
> Functional components should work if they are the default export of the passed in fil

Ah, did not know this. Thanks!
